<?php

namespace rest\program;

class ProgramParams
{
    public array $field_types_of_mentoring;
    public string $field_types_of_mentoring_other;
    public array $field_program_operated_through;
    public string $field_program_operated_other;
    public string $field_facebook;
    public string $field_twitter;
    public string $field_website;
    public string $field_instagram;
    public string $field_focus_area;
    public string $field_focus_area_other;
    public string $field_primary_meeting_location;
    public string $field_primary_meeting_loc_other;
    public array $field_program_how_are_meetings_s;
    public string $field_program_how_other;
    public array $field_program_genders_served;
    public string $field_program_genders_other;
    public array $field_program_ages_served;
    public string $field_program_ages_other;
    public array $field_program_family_served;
    public string $field_program_family_other;
    public array $field_program_youth_served;
    public string $field_program_youth_other;
    public string $field_program_youth_per_year;
    public string $field_program_mentees_waiting_li;
    public array $field_program_gender_mentor_targ;
    public string $field_program_gender_mentor_oth;
    public array $field_program_ages_mentor_target;
    public string $field_program_age_mentor_other;
    public string $field_program_mentor_month_commi;
    public string $field_program_mentor_month_other;
    public string $field_program_mentor_freq_commit;
    public string $field_program_mentor_freq_other;
    public string $field_program_mentor_hour_commit;
    public string $field_program_mentor_hour_other;
    public string $field_program_screens_mentors;
    public array $field_program_screens_mentors_ho;
    public string $field_program_screens_mentees;
    public array $field_program_screens_mentees_ho;
    public string $field_program_trains_mentors;
    public array $field_program_trains_mentors_how;
    public string $field_program_must_train_mentors;
    public string $field_program_trains_mentees;
    public array $field_program_trains_mentees_how;
    public string $field_program_must_train_mentees;
    public array $field_program_matches_how;
    public string $field_program_matches_explain;
    public string $field_program_ongoing_support;
    public string $field_program_beginning_and_end;
    public string $field_program_has_specific_goals;
    public array $field_program_which_goals;
    public string $field_program_which_goals_other;
    public string $field_feedback;
    public array $field_program_accepting;
    public string $field_ns_bg_check;
    public array $field_ns_bg_check_types;
    public string $field_ns_bg_fingerprint_type;
    public string $field_ns_bg_name_type;
    public string $field_ns_bg_peer_type;
    public array $field_ns_bg_other_types;
    public string $field_ns_training;
    public array $field_program_grades_served;
    public string $field_display_title;
    public string $field_description;
    public string $field_mentor_role_description;
    public string $field_ns_training_description;
    public string $title;
}
